#!/bin/bash

logfile=/app/out
exec >> "${logfile}" 2>&1

set -x

set -o errexit
set -o pipefail
set -o nounset

##
# Node.js dependencies hook.
#

cd /app/src

dependenciesPath=/app/.shipbuilder

mkdir -p "${dependenciesPath}"

if [ -r 'package.json' ] ; then
    if [ -L 'node_modules' ] ; then
        unlink node_modules
    elif [ -d 'node_modules' ] ; then
        rm -rf node_modules
    fi

    cp package.json "${dependenciesPath}"

    cd "${dependenciesPath}"

    echo '--> Installing npm dependencies'
    stdbuf -o0 npm install 2>&1

    ln -s "${dependenciesPath}/node_modules" /app/src/node_modules

else
    echo 'warning: no "packages.json" file found'
fi

echo "RETURN_CODE: 0"
exit 0
