#!/bin/bash

##
# Python dependencies hook.
#

function abortIfNonZero() {
    # @param $1 command return code/exit status (e.g. $?, '0', '1').
    # @param $2 error message if exit status was non-zero.
    local rc=$1
    local what=$2
    test $rc -ne 0 && echo "error: ${what} exited with non-zero status ${rc}" >> /app/out && exit $rc || :
}

cd /app/src
abortIfNonZero $? 'Changing directory to "/app/src"'

dependenciesPath='/app/.shipbuilder/.m2/repository'

test ! -d "${dependenciesPath}" && mkdir -p "${dependenciesPath}"

# Support sbt-assembly deployments, @see https://github.com/sbt/sbt-assembly for more information.
stdbuf -o0 mvn clean install -DskipTests 2>&1 >> /app/out
rc=$?
abortIfNonZero $rc '`mvn clean install` failed'

echo "RETURN_CODE: ${rc}" >> /app/out
exit $rc
