#!/bin/bash

set -o nounset

logfile=/app/out
exec > "${logfile}" 2>&1

##
# Java 8 app dependencies and build hook.
#

function abortIfNonZero() {
    # @param $1 command return code/exit status (e.g. $?, '0', '1').
    # @param $2 error message if exit status was non-zero.
    local rc=${1:-}
    local what=${2:-}
    if [ ${rc} -ne 0 ] ; then
        echo "error: ${what} exited with non-zero status ${rc}"
        echo "RETURN_CODE: ${rc}"
        exit ${rc}
    fi
}

cd /app/src
abortIfNonZero $? 'Changing directory to "/app/src"'

dependenciesPath='/app/.shipbuilder/.m2/repository'

mkdir -p "${dependenciesPath}"
abortIfNonZero $? 'Creating directory dependenciesPath=${dependenciesPath}'

# Support sbt-assembly deployments, @see https://github.com/sbt/sbt-assembly for more information.
stdbuf -o0 mvn clean install -DskipTests 2>&1
rc=$?
abortIfNonZero ${rc} "Command 'mvn clean install -DskipTests'"

echo "RETURN_CODE: ${rc}"
exit ${rc}
